# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(blank=True, choices=[('PC Portable', 'PC Portable'), ('Video Proj', 'Video Proj'), ('Clavier', 'Clavier'), ('Souris', 'Souris'), ('Camera', 'Camera')], default='PC Portable', related_name='select_equipment', to='mycalendarapp.WorkshopEvent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event')),
                ('room', models.ManyToManyField(blank=True, choices=[('Centre Multimedia', 'Centre Multimedia'), ('Espace Co-working', 'Espace Co-working'), ('Salle de Reunion Formation', 'Salle de Reunion Formation'), ('FabLab', 'FabLab')], default='FabLab', related_name='select_room', to='mycalendarapp.WorkshopEvent')),
            ],
        ),
    ]
