# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-07 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Animator',
        ),
    ]
