# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0002_auto_20190201_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopevent',
            name='animator',
        ),
    ]
