# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0002_auto_20190121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_events', to='schedule.Event'),
        ),
    ]
