# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0003_remove_workshopevent_animator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopevent',
            name='equipment',
            field=models.ManyToManyField(choices=[('PC Portable', 'PC Portable'), ('Video Proj', 'Video Proj'), ('Clavier', 'Clavier'), ('Souris', 'Souris'), ('Camera', 'Camera')], default='PC Portable', related_name='select_equipment', to='mycalendarapp.WorkshopEvent'),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='room',
            field=models.ManyToManyField(choices=[('Centre Multimedia', 'Centre Multimedia'), ('Espace Co-working', 'Espace Co-working'), ('Salle de Reunion Formation', 'Salle de Reunion Formation'), ('FabLab', 'FabLab')], default='FabLab', related_name='select_room', to='mycalendarapp.WorkshopEvent'),
        ),
    ]
