# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-18 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0003_auto_20190211_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
