# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0004_auto_20190201_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopevent',
            name='equipment',
            field=models.ManyToManyField(related_name='select_equipment', to='mycalendarapp.WorkshopEvent'),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='room',
            field=models.ManyToManyField(related_name='select_room', to='mycalendarapp.WorkshopEvent'),
        ),
    ]
